name: Book CIRCUIT TRAINING for Thursday 17:45
on:
    workflow_dispatch:
    schedule:
        - cron: '25 15 * * 2' # Runs every Tuesday at 17:25h to book class for Thursday 17:45 // 1h difference with server.

jobs:
    invoke-template:
        uses: ./.github/workflows/template.yml
        with:
            activity: 'CIRCUIT TRAINING'
            activity_time: '17:45'
        secrets:
            BASE_URL: ${{ secrets.BASE_URL }}
            GYMUSERNAME: ${{ secrets.GYMUSERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
