name: Book CIRCUIT TRAINING TALAIA for Thursday 15:15
on:
    workflow_dispatch:
    schedule:
        - cron: '55 13 * * 2' # Runs every Tuesday at 14:55h to book class for Thursday 15:15 // 1h difference with server.

jobs:
    invoke-template:
        uses: ./.github/workflows/template.yml
        with:
            activity: 'CIRCUIT TRAINING TALAIA'
            activity_time: '15:15'
        secrets:
            base_url: ${{ secrets.BASE_URL }}
            gymusername: ${{ secrets.GYMUSERNAME }}
            password: ${{ secrets.PASSWORD }}
