name: Book CIRCUIT TRAINING for Monday 17:45
on:
    workflow_dispatch:
    schedule:
        - cron: '25 15 * * 6' # Runs every Saturday at 17:25h to book Class for  Monday 18h // 1h difference with server.

jobs:
    invoke-template:
        uses: ./.github/workflows/template.yml
        with:
            activity: 'CIRCUIT TRAINING'
            activity_time: '17:45'
        secrets:
            BASE_URL: ${{ secrets.BASE_URL }}
            GYMUSERNAME: ${{ secrets.GYMUSERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
