name: Book CROSS TRAINING for TUE 17:45
on:
    workflow_dispatch:
    schedule:
        - cron: '35 15 * * 0' # Runs every Sunday at 17:35h Spain Time to book the class for tuesday at 17:45 // Summer time 2h diff

jobs:
    invoke-template:
        uses: ./.github/workflows/template.yml
        with:
            activity: 'CROSS TRAINING'
            activity_time: '17:45'
        secrets:
            BASE_URL: ${{ secrets.BASE_URL }}
            GYMUSERNAME: ${{ secrets.GYMUSERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
