name: Book CROSS TRAINING for Tuesday 17:45
on:
    workflow_dispatch:
    schedule:
        - cron: '25 16 * * 0' # Runs every Sunday at 17:25h to book class for Tuesday at 17:45 // 1h difference with server.

jobs:
    invoke-template:
        uses: ./.github/workflows/template.yml
        with:
            activity: 'CROSS TRAINING'
            activity_time: '17:45'
        secrets:
            BASE_URL: ${{ secrets.BASE_URL }}
            GYMUSERNAME: ${{ secrets.GYMUSERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
