name: Book CROSS TRAINING for Tuesday 17:45
on:
    workflow_dispatch:
    schedule:
        - cron: '30 15 * * 0' # Runs every Sunday at 17:30h // 2h difference with server.

jobs:
    invoke-template:
        uses: ./.github/workflows/template.yml
        with:
            activity: 'CROSS TRAINING'
            activity_time: '17:45'
        secrets:
            base_url: ${{ secrets.BASE_URL }}
            gymusername: ${{ secrets.GYMUSERNAME }}
            password: ${{ secrets.PASSWORD }}
