name: Book CROSS TRAINING for Friday 17:30
on:
    workflow_dispatch:
    schedule:
        - cron: '15 16 * * 3' # Runs every Wednesday at 17:15h // 2h difference with server.

jobs:
    invoke-template:
        uses: ./.github/workflows/template.yml
        with:
            activity: 'CROSS TRAINING'
            activity_time: '17:30'
        secrets:
            base_url: ${{ secrets.BASE_URL }}
            gymusername: ${{ secrets.GYMUSERNAME }}
            password: ${{ secrets.PASSWORD }}
