name: Book CIRCUIT TRAINING for Monday 07:00

on:
    workflow_dispatch:
    schedule:
        - cron: '45 4 * * 6' # Runs every Saturday at 06:45h // 2h difference with server.

jobs:
    invoke-template:
        uses: ./.github/workflows/template.yml
        with:
            activity: 'CIRCUIT TRAINING'
            activity_time: '07:00'
        secrets:
            base_url: ${{ secrets.BASE_URL }}
            gymusername: ${{ secrets.GYMUSERNAME }}
            password: ${{ secrets.PASSWORD }}
