name: Book CIRCUIT TRAINING for Wednesday 18:00
on:
    workflow_dispatch:
    schedule:
        - cron: '50 16 * * 1' # Runs every Monday at 17:45h // 2h difference with server.

jobs:
    invoke-template:
        uses: ./.github/workflows/template.yml
        with:
            activity: 'CIRCUIT TRAINING'
            activity_time: '18:00'
        secrets:
            base_url: ${{ secrets.BASE_URL }}
            gymusername: ${{ secrets.GYMUSERNAME }}
            password: ${{ secrets.PASSWORD }}
