name: Book CROSS TRAINING for Friday 17:30
on:
    workflow_dispatch:
    schedule:
        - cron: '10 15 * * 3' # Runs every Wednesday at 17:10h to book Class for Friday at 17:30 // 1h difference with server.

jobs:
    invoke-template:
        uses: ./.github/workflows/template.yml
        with:
            activity: 'CROSS TRAINING'
            activity_time: '17:30'
        secrets:
            BASE_URL: ${{ secrets.BASE_URL }}
            GYMUSERNAME: ${{ secrets.GYMUSERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
