name: Book CIRCUIT TRAINING for Thursday 17:45
on:
    workflow_dispatch:
    schedule:
        - cron: '30 15 * * 2' # Runs every Tuesday at 17:45h // 2h difference with server.

jobs:
    invoke-template:
        uses: ./.github/workflows/template.yml
        with:
            activity: 'CIRCUIT TRAINING'
            activity_time: '17:45'
        secrets:
            base_url: ${{ secrets.BASE_URL }}
            gymusername: ${{ secrets.GYMUSERNAME }}
            password: ${{ secrets.PASSWORD }}
