name: Playground Workflow to test changes before merging to master.
on:
    workflow_dispatch:
        inputs:
            activity:
                description: 'Activity to book'
                required: true
            activity_time:
                description: 'Time to book the activity'
                required: true
            days_ahead:
                description: 'Days ahead to check the activity calendar'
                required: false
                default: 2

jobs:
    invoke-template:
        uses: ./.github/workflows/template.yml
        with:
            activity: ${{ inputs.activity }}
            activity_time: ${{ inputs.activity_time }}
            days_ahead: ${{ inputs.days_ahead }}
        secrets:
            base_url: ${{ secrets.BASE_URL }}
            gymusername: ${{ secrets.GYMUSERNAME }}
            password: ${{ secrets.PASSWORD }}
