name: Playground Workflow to test changes before merging to master.
on:
    workflow_dispatch:

jobs:
    invoke-template:
        uses: ./.github/workflows/template.yml
        with:
            activity: 'LES MILLS TONE'
            activity_time: '15:15'
        secrets:
            base_url: ${{ secrets.BASE_URL }}
            gymusername: ${{ secrets.GYMUSERNAME }}
            password: ${{ secrets.PASSWORD }}
