name: Template

on:
    workflow_call:
        inputs:
            activity:
                description: 'Activity name, aka the class to book'
                required: true
                type: string
            activity_time:
                description: 'Time of the activity on the schedule of the gym in the format HH:MM'
                required: true
                type: string
            days_ahead:
                description: 'Days ahead to check the activity calendar of the gym'
                required: false
                default: 2
                type: number
        secrets:
            BASE_URL:
                required: true
            GYMUSERNAME:
                required: true
            PASSWORD:
                required: true

env:
    BASE_URL: ${{ secrets.BASE_URL }}
    GYMUSERNAME: ${{ secrets.GYMUSERNAME }}
    PASSWORD: ${{ secrets.PASSWORD }}
    ACTIVITY: ${{ inputs.activity }}
    ACTIVITY_TIME: ${{ inputs.activity_time }}
    DAYS_AHEAD: ${{ inputs.days_ahead }}

jobs:
    test:
        timeout-minutes: 20
        runs-on: ubuntu-latest
        steps:
            - name: Show current time for debugging purposes
              run: TZ="Europe/Madrid" date +"%Y-%m-%d %H:%M:%S"
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: npm ci
            - name: Run booking script
              run: npm run booking
